### PR TITLE
Fixes containerization of client

### PR DESCRIPTION
**Pull request by Badrri-Narayanan**
## Description
Fixes containerization of client. Makes local setup and further development of front-end easier.

## Issue ticket number and link

closes #260 

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

## Other Stuff

this a workaround and is related to [this PR](https://github.com/USEPA/haztrak/pull/260)

### CODE REVIEW

**Comment by dpgraham4401** [comment]
@Badrri-Narayanan Thanks for the PR! 

Do you mind if I make some modifications?

I think you're on the right track but I think we can do this without removing the contents of the Dockerfile.

**Review by dpgraham4401 — CHANGES_REQUESTED** [review]
We can do this another way but keeping the ./client/Dockerfile intact (since it's responsible for building the image for deploying to production). 

If we use the below in our docker-compose.yaml, the result is the same.
```yaml
  client:
    image: "node:16"
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    environment:
      REACT_APP_HT_API_URL: ${REACT_APP_HT_API_URL}
      REACT_APP_HT_ENV: ${REACT_APP_HT_ENV}
    command: sh -c "cd /app; npm install; npm start"
```

I've tested this, It does work on my linux/MacOS workstations. The only thing is it takes a little while to start up the first time since npm automatically updates the package-lock.json file version to version 2 (which is OK with me, but I'm not 100% certain if it's backwards compatible with older npm versions.

**Comment by Badrri-Narayanan** [comment]
@dpgraham4401 I don't mind at all. Please continue with your changes.

**Comment by dpgraham4401** [comment]
@Badrri-Narayanan I'm realizing I cannot push to this branch, vs code in the browser is also not working. Can you make the proposed modifications? I'd like to get your PR in here so we can get back to the fun stuff :)

**Comment by Badrri-Narayanan** [comment]
@dpgraham4401 sure thing

**Comment by Badrri-Narayanan** [comment]
@dpgraham4401 I have done the changes as you advised

**Review by dpgraham4401 — APPROVED** [review]
Love it!

**Pull request merged**
