### PR TITLE
[Feat] Add haztrak logo in login screen

### PR DESCRIPTION
**Pull request by nirajpdn**
PR for issue #157 

Screenshot 👇🏻

Screen Shot 2022-11-10 at 07 22 22

### CODE REVIEW

**Comment by dpgraham4401** [comment]
@nirajpdn mind if I tag team this one with you? I'd like to see what it looks like with a few tweaks.

**Review by dpgraham4401 — COMMENTED** [review]
I guess you're using JetBrains stuff as well? I've never really committed these kind of files to VCS before, but I'm glad they're coming in handy. 

We have another run config for using the celery service as standalone container, [/.idea/runConfigurations/Celery.xml](https://github.com/USEPA/haztrak/blob/main/.idea/runConfigurations/Celery.xml) Is that one not working? This looks like it replicates that exactly.

**Comment by nirajpdn** [comment]
> @nirajpdn mind if I tag team this one with you? I'd like to see what it looks like with a few tweaks.

@dpgraham4401 , Please let me know the changes i need to do for now.

**Comment by nirajpdn** [comment]
> I guess you're using JetBrains stuff as well? I've never really committed these kind of files to VCS before, but I'm glad they're coming in handy.

I don't use JetBrains.
> We have another run config for using the celery service as standalone container, [/.idea/runConfigurations/Celery.xml](https://github.com/USEPA/haztrak/blob/main/.idea/runConfigurations/Celery.xml) Is that one not working? This looks like it replicates that exactly.
I have also noticed but, it is working fine. I really don't have much idea about such configurations. Thanks for letting me know.

**Review by dpgraham4401 — CHANGES_REQUESTED** [review]
@nirajpdn can you please make the following changes
1. revert changes celery.xml
2. move the new logo to the top left corner. 

Let me know if you'd prefer that I make these changes, I hate to nit pick and I'm happy to co-commit with you. 

Thanks in advance!

**Pull request closed without merging**
