### PR TITLE
pull request error fix

### PR DESCRIPTION
**Pull request by ayobamiseun**

### CODE REVIEW

**Comment by dpgraham4401** [comment]
@ayobamiseun The client side tests are still not passing, It looks like there are some problems with the dependencies specifed in the lock file. [See the error output from the tests](https://github.com/USEPA/haztrak/actions/runs/3468083546/jobs/5793550824#step:4:7).

You can use git to revert the lock file to to the commit prior to your first commit, or remove the lock file and run `npm install .` while in the `client` directory (i'd prefer the former for a cleaner PR but whatever works). 

On the implementation, we're looking for a single subcomponent instead of 2 seperate subcomponents, that we can pass the necesarry navigation links as props. That way if we make future changes, for example to the style of this dropdown or decide to add another, we only have to change it in one place, the new subcomponenet. 

Does that make sense? If I need to clarify, let me know. Maybe I can find a blog post about it or something.

**Review by dpgraham4401 — CHANGES_REQUESTED** [review]
@ayobamiseun The client side tests are still not passing, It looks like there are some problems with the dependencies specifed in the lock file. [See the error output from the tests](https://github.com/USEPA/haztrak/actions/runs/3468083546/jobs/5793550824#step:4:7).

You can use git to revert the lock file to to the commit prior to your first commit, or remove the lock file and run `npm install .` while in the `client` directory (i'd prefer the former for a cleaner PR but whatever works). 

On the implementation, we're looking for a single subcomponent instead of 2 seperate subcomponents, that we can pass the necesarry navigation links as props. That way if we make future changes, for example to the style of this dropdown or decide to add another, we only have to change it in one place, the new subcomponenet. 

Does that make sense? If I need to clarify, let me know. Maybe I can find a blog post about it or something.

**Comment by ayobamiseun** [comment]
I have a lot of commit behind and it's stopping me from pushing further. I love it tho cause I am learning a lot, thanks for your patient.

**Comment by dpgraham4401** [comment]
@ayobamiseun have you been testing locally before pushing?

> it's stopping me from pushing further

How about we close this PR, make sure things are passing the test locally before pushing? thanks

**Comment by ayobamiseun** [comment]
The recent push worked thanks

**Pull request closed without merging**
